name: Java CI

on: [push]

jobs:

  build_faiss:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@master
      with:
        submodules: true

    - uses: whoan/docker-build-with-cache-action@v5
      with:
        username: kdiduk
        password: "${{ secrets.GITHUB_TOKEN }}"
        registry: docker.pkg.github.com
        #or
        #registry: ghcr.io
        image_name: jfaiss-cpu
        dockerfile: Dockerfile

    # - name: Run the docker image
    #   uses: ./.github/actions

    # - name: Debugging with tmate
    #   uses: mxschmitt/action-tmate@v3

    # - run: docker image ls

    - run: docker run -v "/home/runner/work/JFaiss-CPU/JFaiss-CPU":"/github/workspace" docker.pkg.github.com/kdiduk/jfaiss-cpu/jfaiss-cpu

    - uses: actions/upload-artifact@v4
      with:
        name: faiss_JNI_and_SO
        path: build
    

  build:
    needs: build_faiss
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Download build
        uses: actions/download-artifact@v2
        with:
          name: faiss_JNI_and_SO
          path: build_copy
      - name: Move
        run: |
          rm -rf src/main/java/com/vectorsearch/faiss/swig
          cp -r build_copy/java/com/vectorsearch/faiss/swig src/main/java/com/vectorsearch/faiss/swig
          rm -rf src/main/resources
          cp -r build_copy/resources src/main/resources

      # - name: Debugging with tmate
      #   uses: mxschmitt/action-tmate@v3

      # - name: Publish package
      #   run: mvn -B deploy
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release Maven package
        uses: samuelmeuli/action-maven-publish@v1
        with:
          gpg_private_key: ${{ secrets.gpg_private_key }}
          gpg_passphrase: ${{ secrets.gpg_passphrase }}
          nexus_username: ${{ secrets.nexus_username }}
          nexus_password: ${{ secrets.nexus_password }}
        env:
          GPG_TTY: $(tty)